POST http://localhost:3000/posts
Content-Type: application/json


{
    "title": "Healthy Eating: A Beginner's Guide",
    "postType": "page",
    "slug": "healthy-eating-beginners-guide",
    "status": "publish",
    "content": "Learn the basics of healthy eating and nutrition.",
    "schema": "{\"type\":\"blog\",\"categories\":[\"health\",\"nutrition\"]}",
    "featuredImageUrl": "https://example.com/healthy-eating.jpg",
    "publishingOn": "2025-03-10T10:00:00Z",
    "tags": [3],
    "metaOption": {
      "metaValue": "{ \"author\": \"Jamie\"}"
    },
    "authorId": 4
  }