POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Archer",
  "email": "archer@example.com",
  "password": "Strong#2024"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json

{
  "users": [
  {
  "firstName": "Martin",
  "email": "martin@example.com",
  "password": "Strong#2024"
}
]}
